#THIS FILE MUST CONTAIN ALL THE CONFIGURATION VARIABLES! as it will be used as the default configs so it must initialize all of them.

production:
  loglevel: info
  #logfile: './logs/pro-logs.log'
  strict: false
  router: true
  validator: true
  ignoreUnknownFormats: true

development:
  loglevel: debug
  #logfile: './dev-logs.log' #if dir is specified before file: EXCEPTION
  strict: true
  router: true
  validator: true
  ignoreUnknownFormats: true
